Feat/creating registration route
VadimShkedov/hospitalBackend pull request #2
Opened 2023-12-23 18:48 UTC by VadimShkedov

2023-12-25 06:42 UTC, baklanovairina requested changes

2023-12-25 06:42 UTC, baklanovairina commented on controllers/user-controllers.js
> +const registrationController = async (req, res, next) => {
ну не надо здесь использовать в нейминге Controller, это излишне, т к и так ясно, что это контроллер, мы в файле user-controllers находимся

2023-12-25 06:42 UTC, baklanovairina commented on controllers/user-controllers.js
> +    if (!errors.isEmpty()) {
это мидлвар
уже проходили и писали его

2023-12-25 06:42 UTC, baklanovairina commented on controllers/user-controllers.js
> +    const { user, tokens } = await registrationService(login, password);
зачем здесь деструктуризация? Это излишне, можно работать с объектом просто, например 
`const newUser = await registrationService(login, password);`

2023-12-25 06:42 UTC, baklanovairina commented on controllers/user-controllers.js
> +    res.cookie('refreshToken', tokens.refresh_token, { maxAge: 2592000000, httpOnly: true });
refresh_token - откуда в нейминге появилось нижнее подчеркивание?

2023-12-25 06:42 UTC, baklanovairina commented on controllers/user-controllers.js
> +    res.cookie('refreshToken', tokens.refresh_token, { maxAge: 2592000000, httpOnly: true });
этот объект 
{ maxAge: 2592000000, httpOnly: true }
выноси в константы в этом файле выше, как глобальные
кроме того откуда это 2592000000 число? Вообще не ясно как оно считается, также в комментарии лучше указать сколько это часов/дней

2023-12-25 06:42 UTC, baklanovairina commented on controllers/user-controllers.js
> +    return res.status(200).json({
сюда просто объект передаешь, без всяких деструктуризаций
`res.status(200).json(newUser);`

2023-12-25 06:42 UTC, baklanovairina commented on exceptions/api-errors.js
> +  message;
это зачем? Ты через супер его получаешь?

2023-12-25 06:42 UTC, baklanovairina commented on exceptions/api-errors.js
> +    this.message = message;
и здесь это лишнее писать

2023-12-25 06:42 UTC, baklanovairina commented on middlewares/error-middleware.js
> +  return res.status(500).send('Непредвиденная ошибка');
`message: 'Непредвиденная ошибка'`

2023-12-25 06:42 UTC, baklanovairina commented on middlewares/registration-middleware.js
> +    .notEmpty(),
читай задание, та не просто пустое поле

2023-12-25 06:42 UTC, baklanovairina commented on middlewares/registration-middleware.js
> +    .isLength({ min: 4, max: 10 }),
читай задание

2023-12-25 06:42 UTC, baklanovairina commented on services/token-service.js
> +  await Token.create({ token, userId });
как будто бы функция не закончена
тебе как минимум нужно сначала проверить существует ли рефреш в базе и только потом его создавать, если нет, а если есть, то перезаписать

2023-12-25 06:42 UTC, baklanovairina commented on services/user-service.js
> +  const tokens = generateTokens({...user});
const tokens = generateTokens({ ...user });

2023-12-25 06:42 UTC, baklanovairina commented on controllers/user-controllers.js
> +    res.cookie('refreshToken', tokens.refresh_token, { maxAge: 2592000000, httpOnly: true });
а где создание акцесс токена??

2023-12-25 11:02 UTC, baklanovairina requested changes

2023-12-25 11:02 UTC, baklanovairina commented on services/user-service.js
> +module.exports = registrationService;
так с только сейчас заметила, а где папка src??

2023-12-25 11:15 UTC, VadimShkedov commented on services/token-service.js
> +  const accessToken = jwt.sign(payload, SECRET_ACCESS_KEY, { expiresIn: MAX_ACCESS_TOKEN_LIFETIME });
в expiresIn можно число в миллисекундах передавать вроде как

2024-01-09 07:13 UTC, baklanovairina requested changes

2024-01-09 07:13 UTC, baklanovairina commented on app.js
> +app.use(cors({ credentials: true, origin: "http://localhost:3000" }))
опции r орсов пишутся в config
а http://localhost:3000 вообще в env

2024-01-09 07:13 UTC, baklanovairina commented on app.js
зачем ты отступы между импортами делаешь?

2024-01-09 07:13 UTC, baklanovairina commented on constants.js
> +const ACCESS_TOKEN_COOKIE_OPTIONS = { maxAge: MAX_ACCESS_TOKEN_LIFETIME, httpOnly: true, sameSite: 'none' }
это же объект, не пиши его пожалуйста в одну строку, свойства так тяжело читаются

2024-01-09 07:13 UTC, baklanovairina commented on src/controllers/user-controllers.js
> +    return res.status(200).json(newUser);
return здесь излишен

2024-01-09 07:13 UTC, baklanovairina commented on src/middlewares/registration-middleware.js
> +    .isString()
а trim ?
лучше дописать и здесь

2024-01-09 07:13 UTC, baklanovairina commented on src/routes/user.js
> +
лишний отступ

2024-01-09 07:13 UTC, baklanovairina commented on src/services/token-service.js
> +
лишний отступ

2024-01-09 07:13 UTC, baklanovairina commented on src/services/user-service.js
> +
лишний отступ

2024-01-09 08:14 UTC, closed without merging

2024-01-09 08:42 UTC, baklanovairina commented on constants.js
> +  credentials: true,
не в константах, в конфигах

2024-01-09 08:42 UTC, baklanovairina commented on app.js
> +const { CORS_OPTIONS } = require('./constants')
;

2024-01-09 08:42 UTC, baklanovairina commented on src/controllers/user-controllers.js
> +    return res.status(200).json(newUser);
не удалил return